version: "3.8"

services:
  chepi-back:
    build: .
    ports:
      - 3000:3000
    environment:
      - ES_URL=http://chepi-es:9200
    depends_on:
      - chepi-es
    profiles:
      - production

  chepi-es:
    image: elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  es-data:
