name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: okteto/login@main
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Create namespace
        uses: okteto/namespace@main

      - name: Deploy pipeline
        uses: okteto/pipeline@main
        with:
          name: chepi-back
