name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Create namespace
        uses: okteto/namespace@latest
        with:
          name: allohamora

      - name: Deploy pipeline
        uses: okteto/pipeline@latest
        with:
          name: chepi-back
